/* PERCENTAGES AND PROPORTIONS */
export const DATA_TO_CONTENT_PROPORTION = 0.9;
export const AXIS_LABEL_FONT_SIZE = '0.75em';

/* COORDINATE-BASED LENGTHS */
export const DATA_MARGIN_TOP = 50;
export const DATA_MARGIN_RIGHT = 20;
export const DATA_MARGIN_BOTTOM = 50;
export const DATA_MARGIN_LEFT = 150;
export const INFOBOX_X_OFFSET_LEFT = -175;
export const INFOBOX_X_OFFSET_RIGHT = 10;
export const INFOBOX_Y_OFFSET_TOP = -175;
export const INFOBOX_Y_OFFSET_BOTTOM = -20;
export const AIRPLANE_ICON_WIDTH = 25;
export const AIRPLANE_ICON_HEIGHT = 15;
export const Y_AXISLABEL_Y_OFFSET = 180;
export const Y_AXISLABEL_X_OFFSET = 50;
export const X_AXISLABEL_Y_OFFSET = 50;

/* DURATIONS (IN MS) */
export const INFOBOX_FADEINOUT_DURATION = 500;
export const AIRPLANE_ICON_EXIT_DURATION = 1000;
export const AIRPLANE_ICON_ENTER_DURATION = 2000;
export const AIRPLANE_ICON_UPDATE_DURATION = 4000;
export const GRAPH_FADEIN_DURATION = 500;

/* AXES AND SCALES */
export const MAX_ALTITUDE = 42000;
export const Y_AXIS_TICK_COUNT = 9;
export const X_AXIS_TICK_COUNT = 10;
